version: "3.9"

services:
  db:
    platform: linux/x86_64 # M2チップだとarm64なので不整合
    image: mysql:8.0.28 # AWS Auroraを使う可能性がある為、互換性があるものを使用
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      TZ: 'Asia/Tokyo'
    command: mysqld --innodb_use_native_aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 50

  api:
    container_name: "api"
    volumes:
      - ./app:/app
    build: ./
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DATABASE: database
      DB_USER: db-user
      DB_PASSWORD: db-pass
      DB_HOST: db
      DB_PORT: '3306'
    ports:
      - 8080:8080
